pub mod agenda;
pub mod app;
pub mod bootstrap;
pub mod claude;
pub mod cli;
mod dashboard;
pub mod git;
pub mod model_confusions;
pub mod openspec;
pub mod process;
pub mod sidecar;
pub mod skills;
pub mod state;
pub mod stream;
pub mod ui;
